### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by mweng1024** [CMSgov/qpp-conversion-tool#1016]
### Information
- OS & version: macOS Catalina
- Java version: openjdk version "1.8.0_262"
- Docker version if using: *(Run `$ docker -v`.)*

### Expected behavior
*(Please be more descriptive than "This file should have created valid QPP."
Also, if you can attach a sample QRDA3 file ***without*** Personally Identifiable Information, that will make triage easier.)*

### Actual behavior
*(Please be more descriptive than "This file didn't create valid QPP.")*
We got Build failed error when we try convert XML to Json

❯ ./convert.sh ./qpp/test.XML
Jar not found. Building...
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] QPP Conversion Tool                                                [pom]
[INFO] Test Commons                                                       [jar]
[INFO] Commons                                                            [jar]
[INFO] generate-maven-plugin                                     [maven-plugin]
[INFO] Converter                                                          [jar]
[INFO] Commandline Converter Extension                                    [jar]
[INFO] RESTful Converter Extension                                        [jar]
[INFO]
[INFO] ---------< gov.cms.qpp.conversion:qpp-conversion-tool-parent >----------
[INFO] Building QPP Conversion Tool 4.1.0-RELEASE                         [1/7]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] ----------------< gov.cms.qpp.conversion:test-commons >-----------------
[INFO] Building Test Commons 4.1.0-RELEASE                                [2/7]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ test-commons ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/mweng/Documents/qpp-conversion-tool-develop/test-commons/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ test-commons ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 19 source files to /Users/mweng/Documents/qpp-conversion-tool-develop/test-commons/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/mweng/Documents/qpp-conversion-tool-develop/test-commons/src/main/java/gov/cms/qpp/test/annotations/ParameterizedAcceptanceTest.java:[5,28] cannot access java.lang.annotation.Retention
  bad class file: /modules/java.base/java/lang/annotation/Retention.class
    class file has wrong version 58.0, should be 53.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for QPP Conversion Tool 4.1.0-RELEASE:
[INFO]
[INFO] QPP Conversion Tool ................................ SUCCESS [  0.004 s]
[INFO] Test Commons ....................................... FAILURE [  3.146 s]
[INFO] Commons ............................................ SKIPPED
[INFO] generate-maven-plugin .............................. SKIPPED
[INFO] Converter .......................................... SKIPPED
[INFO] Commandline Converter Extension .................... SKIPPED
[INFO] RESTful Converter Extension ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.616 s
[INFO] Finished at: 2020-10-05T14:20:02-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project test-commons: Compilation failure
[ERROR] /Users/mweng/Documents/qpp-conversion-tool-develop/test-commons/src/main/java/gov/cms/qpp/test/annotations/ParameterizedAcceptanceTest.java:[5,28] cannot access java.lang.annotation.Retention
[ERROR]   bad class file: /modules/java.base/java/lang/annotation/Retention.class
[ERROR]     class file has wrong version 58.0, should be 53.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :test-commons
Build failed. Aborting.

### Steps to reproduce
1. *(Please include detailed steps.)*
1. Download the repository
2. run "./convert.sh ./qpp/test.XML" in terminal

### Other details
*(Tell us any other details you think are pertinent to this issue.)*

**Comment by saquino0827** [comment]
Please open another issue if the build is still failing with information on what branch you are using. Using the same command with a sample test file on the latest develop and master branches, I get valid builds back.
