### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by dknapp47** [CMSgov/qpp-conversion-tool#1055]
### Information
- OS & version: mac OS 10.14.6
- Java version: 1.8.0_73
- Docker version if using: 20.10.2, build 2291f61

### Expected behavior
"docker-compose -f ./docker-compose.test.yaml up" builds and starts the tool successfully.

### Actual behavior
Fails with this error:

ERROR: Service 'rest' failed to build : The command '/bin/sh -c mvn install -Dmaven.test.skip -Djacoco.skip=true > /dev/null' returned a non-zero code: 1

### Steps to reproduce
1. Download the zip and unpack
2. cs into directory
3. docker-compose -f ./docker-compose.test.yaml up

### Other details
Release 4.3.2 works correctly.

I updated the DockerfileTest to show the errors in that step:

Davids-MacBook-Pro-3:qpp-conversion-tool-develop davidknapp$ docker-compose -f ./docker-compose.test.yaml up
Building rest
Step 1/13 : FROM maven:3.6.3-jdk-11
 ---> 8de5407a7beb
Step 2/13 : RUN mkdir -p /usr/src/app/
 ---> Using cache
 ---> 72ddf9c42aa0
Step 3/13 : RUN mkdir -p /usr/src/run/
 ---> Using cache
 ---> c10d91eb1c15
Step 4/13 : RUN apt-get update && apt-get install dos2unix
 ---> Using cache
 ---> d0798fed55b0
Step 5/13 : COPY ./ /usr/src/app/
 ---> a38778e00693
Step 6/13 : WORKDIR /usr/src/app/
 ---> Running in 46d16605a542
Removing intermediate container 46d16605a542
 ---> 44f84ce2b970
Step 7/13 : RUN mvn install -Dmaven.test.skip -Djacoco.skip=true
 ---> Running in 7fd3c3fbb44c
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Child module /usr/src/app/test-coverage of /usr/src/app/pom.xml does not exist @ 
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project gov.cms.qpp.conversion:qpp-conversion-tool-parent:4.3.2-RELEASE (/usr/src/app/pom.xml) has 1 error
[ERROR]     Child module /usr/src/app/test-coverage of /usr/src/app/pom.xml does not exist
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
ERROR: Service 'rest' failed to build : The command '/bin/sh -c mvn install -Dmaven.test.skip -Djacoco.skip=true' returned a non-zero code: 1

**Comment by saquino0827** [comment]
@dknapp47 This was resolved a few days ago and I forgot to mention this here. Please try again and let me know if you have any more issues.
