### ISSUE TITLE
Submissions for 2021 not working- says needs to comply with 2020 guidelines

### ISSUE THREAD

**Issue by kdd21** [CMSgov/qpp-conversion-tool#1073]
### Information
- OS & version:  Windows 10
- Docker version: Docker version 19.03.8, build afacb8b

### Expected behavior
Trying to use it with test files for 2021 and it appears to be expecting 2020, according to the error we're getting

### Actual behavior
Error message when submitting with a 2021 formatted file:
"The file is not a QRDA-III XML document. Please ensure that the submission complies with the 2020 implementation guide. https://ecqi.healthit.gov/sites/default/files/2020-CMS-QRDA-III-Eligible-Clinicians-and-EP-IG-v1.1-508.pdf#page=19"

### Steps to reproduce
Submit file for 2021

### Other details
Wondering if it's yet been updated for 2021 and if not, what might be the ETA?

**Comment by saquino0827** [comment]
Hi @kdd21 
Conversion of 2021 QRDA-III files has not been updated yet. An ETA will most likely be around August or September before we get public releases out.
