### ISSUE TITLE
Jar not found

### ISSUE THREAD

**Issue by abhisheka1993** [CMSgov/qpp-conversion-tool#1111]
![ErrorLog](https://user-images.githubusercontent.com/55098368/131847104-e36b80d6-deea-43bf-b2ce-8fda67c88af5.jpg)

Getting this error while validating QRDA file, I have already installed JDK but still giving this error. Also it seems the mentioned files are not present in qpp-conversion-tool (commandline/target/commandline.jar). Can someone please do needful here. #1110

**Comment by abhisheka1993** [comment]
Anyone plz connect on this

**Comment by saquino0827** [comment]
Hi @abhisheka1993,
You will need to install Apache Maven version 3.6.3 to run the build commands. Please let me know if any other issues come up.

Samuel Aquino

**Comment by abhisheka1993** [comment]
Hi Samuel,
Thanks for replying, I have already installed Apache Maven version 3.8.2. Attached for reference. I have compared the qpp-conversion-tool with year 2020. It seems the files are present (commandline/target/commandline.jar) in the conversion tool. but in latest qpp-conversion-tool it doesn't have. Could you please let me know any update on this.

Thanks
![Mvn](https://user-images.githubusercontent.com/55098368/132447271-a35ed428-a83b-42f6-8101-7ff38d0c1deb.jpg)

**Comment by saquino0827** [comment]
Hi @abhisheka1993 ,
Looks like you're using Java 8 but Conversion Tool was updated to Java 11. You will need to install and and run the Conversion Tool on Java 11. Let me know if there are still issues afterwards.

Samuel Aquino

**Comment by abhisheka1993** [comment]
Hi Samuel,
I have installed Java 11 but still getting the issue. If possible can you please schedule a meeting so we can check it and fix it easily.
Thanks

Abhishek Avadhoot

**Comment by abhisheka1993** [comment]
Also do you have any comment on error mentioned as  **Unable to access jarfile commandline/target/commandline.jar**. this path is not available in  qpp-conversion-tool

**Comment by saquino0827** [comment]
Hi @abhisheka1993 
A few questions for you before we meet:
1) What branch of conversion tool are you running from? 
2) What commands are you running to get these errors and do you run them in the parent directory?
3) Can you build using `mvn clean package` in the Conversion Tools parent directory?

**Comment by saquino0827** [comment]
@abhisheka1993 
Can you try checking `mvn -v` to see if maven is using the correct version of java?
The `Unable to access jarfile commandline/target/commandline.jar` error is from the `convert.bat` file and it picks up any error received and outputs that error.

**Comment by abhisheka1993** [comment]
Hi,
I have checked now `mvn -v` it was still showing old java version so I have made changes now able to convert file without any issues.
Thanks

**Comment by saquino0827** [comment]
@abhisheka1993 
If you have any more issues, feel free to post them here.
