### ISSUE TITLE
QPP Tool getting failed while install

### ISSUE THREAD

**Issue by Ferozsrs** [CMSgov/qpp-conversion-tool#1113]
Hi Team
while installing qpp getting the below error and it getting failed, Please suggest and attached screenshot

Z:\>cd qpp-conversion-tool-develop

Z:\qpp-conversion-tool-develop>cd qpp-conversion-tool-develop

Z:\qpp-conversion-tool-develop\qpp-conversion-tool-develop>convert.bat qrda-files/valid-QRDA-III.xml
.
"Jar not found. Building..."
.
.
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] QPP Conversion Tool                                                [pom]
[INFO] Test Commons                                                       [jar]
[INFO] Commons                                                            [jar]
[INFO] generate-maven-plugin                                     [maven-plugin]
[INFO] Converter                                                          [jar]
[INFO] Commandline Converter Extension                                    [jar]
[INFO] RESTful Converter Extension                                        [jar]
[INFO] QPP Conversion Tool Test Coverage                                  [pom]
[INFO]
[INFO] ---------< gov.cms.qpp.conversion:qpp-conversion-tool-parent >----------
[INFO] Building QPP Conversion Tool 4.3.3-RELEASE                         [1/8]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.5:prepare-agent (jacoco-initialize) @ qpp-conversion-tool-parent ---
[INFO] argLine set to -javaagent:C:\\Users\\sferoz\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.5\\org.jacoco.agent-0.8.5-runtime.jar=destfile=Z:\\qpp-conversion-tool-develop\\qpp-conversion-tool-develop\\target\\jacoco.exec
[INFO]
[INFO] ----------------< gov.cms.qpp.conversion:test-commons >-----------------
[INFO] Building Test Commons 4.3.3-RELEASE                                [2/8]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.5:prepare-agent (jacoco-initialize) @ test-commons ---
[INFO] argLine set to -javaagent:C:\\Users\\sferoz\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.5\\org.jacoco.agent-0.8.5-runtime.jar=destfile=Z:\\qpp-conversion-tool-develop\\qpp-conversion-tool-develop\\test-commons\\target\\jacoco.exec
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ test-commons ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory Z:\qpp-conversion-tool-develop\qpp-conversion-tool-develop\test-commons\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ test-commons ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 19 source files to Z:\qpp-conversion-tool-develop\qpp-conversion-tool-develop\test-commons\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] javac: invalid target release: 11
Usage: javac <options> <source files>
use -help for a list of possible options

[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for QPP Conversion Tool 4.3.3-RELEASE:
[INFO]
[INFO] QPP Conversion Tool ................................ SUCCESS [01:00 min]
[INFO] Test Commons ....................................... FAILURE [ 13.001 s]
[INFO] Commons ............................................ SKIPPED
[INFO] generate-maven-plugin .............................. SKIPPED
[INFO] Converter .......................................... SKIPPED
[INFO] Commandline Converter Extension .................... SKIPPED
[INFO] RESTful Converter Extension ........................ SKIPPED
[INFO] QPP Conversion Tool Test Coverage .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:14 min
[INFO] Finished at: 2021-09-07T11:54:36+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project test-commons: Compilation failure
[ERROR] javac: invalid target release: 11
[ERROR] Usage: javac <options> <source files>
[ERROR] use -help for a list of possible options
[ERROR]
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :test-commons
""
"Build failed. Aborting."
""
Error: Unable to access jarfile commandline/target/commandline.jar

![image](https://user-images.githubusercontent.com/44632985/132451278-38b71729-c471-4f10-b9eb-2c41561e1409.png)

### Information
- OS & version:
- Java version: *(Run `$ java -version`.)*
- Docker version if using: *(Run `$ docker -v`.)*

### Expected behavior
*(Please be more descriptive than "This file should have created valid QPP."
Also, if you can attach a sample QRDA3 file ***without*** Personally Identifiable Information, that will make triage easier.)*

### Actual behavior
*(Please be more descriptive than "This file didn't create valid QPP.")*

### Steps to reproduce
1. *(Please include detailed steps.)*

### Other details
*(Tell us any other details you think are pertinent to this issue.)*

**Comment by saquino0827** [comment]
Hi @Ferozsrs 
Please provide your OS, Maven version and java version.

Thanks,
Samuel Aquino

**Comment by Ferozsrs** [comment]
Hi @saquino0827 
Please find the details below as requested and please suggest your solution as soon as possible as it required for us to testing, we are planning release...Thanks

Edition	Windows 10 Pro
Version	20H2
Installed on	‎13-‎04-‎2021
OS build	19042.867
Serial number	5CD106L4LX
Experience	Windows Feature Experience Pack 120.2212.551.0

Java version - 1.8.0_291
Maven Version - 3.8.1


![image](https://user-images.githubusercontent.com/44632985/132543701-a17ceee3-d3ca-4deb-86ec-d4787d3a45d5.png)


![image](https://user-images.githubusercontent.com/44632985/132543371-a467222c-c2ce-48ba-ba5b-6096dd3c8cfb.png)

**Comment by saquino0827** [comment]
@Ferozsrs
You will need to use the java version 11 for Conversion Tool as it was updated to Java 11 for this upcoming year.

**Comment by Ferozsrs** [comment]
Hi @saquino0827
Thanks for response, We tried to install qpp in our environment by upgrading java version to V11 but seems like the same type of issue getting. Please suggest

Z:\>c:

C:\>java -version
java version "11.0.12" 2021-07-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.12+8-LTS-237)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.12+8-LTS-237, mixed mode)

C:\>mvn -version
C:\
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: C:\Program Files\apache-maven-3.8.1-bin\apache-maven-3.8.1\bin\..
Java version: 1.8.0_291, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_291\jre
Default locale: en_IN, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

C:\>


![image](https://user-images.githubusercontent.com/44632985/132626305-0e347b51-8600-4f4f-b69c-c52b0ac927f6.png)



Process - 

Z:\qpp-conversion-tool-develop\qpp-conversion-tool-develop>convert.bat qrda-files/valid-QRDA-III.xml
.
"Jar not found. Building..."
.
.
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] QPP Conversion Tool                                                [pom]
[INFO] Test Commons                                                       [jar]
[INFO] Commons                                                            [jar]
[INFO] generate-maven-plugin                                     [maven-plugin]
[INFO] Converter                                                          [jar]
[INFO] Commandline Converter Extension                                    [jar]
[INFO] RESTful Converter Extension                                        [jar]
[INFO] QPP Conversion Tool Test Coverage                                  [pom]
[INFO]
[INFO] ---------< gov.cms.qpp.conversion:qpp-conversion-tool-parent >----------
[INFO] Building QPP Conversion Tool 4.3.3-RELEASE                         [1/8]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.5:prepare-agent (jacoco-initialize) @ qpp-conversion-tool-parent ---
[INFO] argLine set to -javaagent:C:\\Users\\sferoz\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.5\\org.jacoco.agent-0.8.5-runtime.jar=destfile=Z:\\qpp-conversion-tool-develop\\qpp-conversion-tool-develop\\target\\jacoco.exec
[INFO]
[INFO] ----------------< gov.cms.qpp.conversion:test-commons >-----------------
[INFO] Building Test Commons 4.3.3-RELEASE                                [2/8]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.5:prepare-agent (jacoco-initialize) @ test-commons ---
[INFO] argLine set to -javaagent:C:\\Users\\sferoz\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.5\\org.jacoco.agent-0.8.5-runtime.jar=destfile=Z:\\qpp-conversion-tool-develop\\qpp-conversion-tool-develop\\test-commons\\target\\jacoco.exec
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ test-commons ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory Z:\qpp-conversion-tool-develop\qpp-conversion-tool-develop\test-commons\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ test-commons ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 19 source files to Z:\qpp-conversion-tool-develop\qpp-conversion-tool-develop\test-commons\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] javac: invalid target release: 11
Usage: javac <options> <source files>
use -help for a list of possible options

[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for QPP Conversion Tool 4.3.3-RELEASE:
[INFO]
[INFO] QPP Conversion Tool ................................ SUCCESS [  0.559 s]
[INFO] Test Commons ....................................... FAILURE [  0.740 s]
[INFO] Commons ............................................ SKIPPED
[INFO] generate-maven-plugin .............................. SKIPPED
[INFO] Converter .......................................... SKIPPED
[INFO] Commandline Converter Extension .................... SKIPPED
[INFO] RESTful Converter Extension ........................ SKIPPED
[INFO] QPP Conversion Tool Test Coverage .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.514 s
[INFO] Finished at: 2021-09-09T10:37:22+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project test-commons: Compilation failure
[ERROR] javac: invalid target release: 11
[ERROR] Usage: javac <options> <source files>
[ERROR] use -help for a list of possible options
[ERROR]
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :test-commons
""
"Build failed. Aborting."
""
Error: Unable to access jarfile commandline/target/commandline.jar
Z:\qpp-conversion-tool-develop\qpp-conversion-tool-develop>

**Comment by saquino0827** [comment]
@Ferozsrs It looks as if your maven is still trying to use java 1.8. Do you know if you Java Home is set to use 11? 

Samuel Aquino.

**Comment by Ferozsrs** [comment]
Thank You so much @saquino0827 
Sorry, now i set java_home to right path and Now working fine, File converted successfully but i received wraning message, please suggest regarding warning messages(as attached)

![image](https://user-images.githubusercontent.com/44632985/132709506-8da58895-903d-4274-a8dd-2d331d33f56c.png)

![image](https://user-images.githubusercontent.com/44632985/132708787-762e0ad3-f7d7-4afa-aad8-d07befc8c78a.png)

**Comment by saquino0827** [comment]
@Ferozsrs That warning can be ignored for now, it is part of some code refactor work we need from upgrading from java 8 to 11. It should not effect your conversion. Feel free to open this issue or a new issue if any more problems come up.
