### ISSUE TITLE
Conversion error from CMS347v4

### ISSUE THREAD

**Issue by johnmahoneyASC** [CMSgov/qpp-conversion-tool#1135]
### Information
- OS & version:  Windows Server running latest version of QPP-Converter-tool v14.5.0
- Java version: *(Run `$ java -version`.)*
- Docker version if using: *(Run `$ docker -v`.)*

### Expected behavior
Testing qpp convert on 2021 MIPS file including eCQM CMS 347v4 and expecting valid conversion

### Actual behavior
QPP convert on file including 347v4 is generating error on NUM and DENEX with message
"CT - The electronic measure id: CMS347v4 requires a NUMER with the correct UUID of 17D080CB-6211-4E3E-AD9A-DFA623DD6F42. Here is a link to the IG containing all the valid measure ids: https://ecqi.healthit.gov/sites/default/files/2021-CMS-QRDA-III-Eligible-Clinicians-and-EP-IG-v1.3.pdf#page=40",

The file to be converted includes the appropriate populations and UUID according to eCQM specs and the UUID table included in the EP IG, Section 6

### Steps to reproduce
Convert MIPS.xml file attached to case 

### Other details
error.json included from conversion
[CMS347v4-QPP-Convert-Issue.zip](https://github.com/CMSgov/qpp-conversion-tool/files/7373325/CMS347v4-QPP-Convert-Issue.zip)

Thank you

**Comment by saquino0827** [comment]
@johnmahoneyASC just a follow up that this issue has been fixed. Feel free to open an issue if any problems still occur.
