### ISSUE TITLE
 XML file validation issue

### ISSUE THREAD

**Issue by pratikshav13** [CMSgov/qpp-conversion-tool#1237]
### Information
- OS & version: windows 10
- Java version: 11.0.12

### Expected behavior
 XML file should get validate

### Actual behavior
The measure GUID supplied is invalid
![validation_Issue](https://user-images.githubusercontent.com/103094844/161901632-dcd4a79b-b521-4c42-9c16-3adc9167e247.png)

### Steps to reproduce
1.Open Location C:\GitHub\qpp-conversion-tool\qrda-files
2.Place MIPS QPP file under the bove mentioned path
3.Run--> Cmd
4.Set path from cmd C:\GitHub\qpp-conversion-tool using following command.
cd C:\GitHub\qpp-conversion-tool
5.For validating file use below command 
convert.bat .\qrda-files\<filename> 

Please let me know if you have any suggestions for how to resolve this.

**Comment by saquino0827** [comment]
Hi @pratikshav13 
Please try the following file:
`qrda-files/valid-QRDA-III-latest.xml`
Some of the files are out of date and need to be cleaned up.

**Comment by saquino0827** [comment]
@pratikshav13
I also noticed you are using a 2022 file. The conversion tool currently cannot convert PY 2022 measure id's.
