### ISSUE TITLE
Confirmation regarding XML file validation

### ISSUE THREAD

**Issue by pratikshav13** [CMSgov/qpp-conversion-tool#1238]
### Information
- OS & version: Windows 10
- Java version: 11.0.12

### Other details
Could you please let me know when Update the latest Tool for converting XML, I want to validate it?
I want to validate XML file 2022.

**Comment by saquino0827** [comment]
@pratikshav13 I will update this once start accepting 2022 xml files. I don't know the exact timeline but it won't be worked on until at the earliest of June/July 2022.
