### ISSUE TITLE
Confirmation regarding XML file validation

### ISSUE THREAD

**Issue by pratikshav13** [CMSgov/qpp-conversion-tool#1274]
Information
OS & version: Windows 10
Java version: 11.0.12
Other details
Could you please let me know when Update the latest Tool for converting XML, I want to validate it?
I want to validate XML file 2022.

**Comment by pratikshav13** [comment]
@saquino0827 Can you please share updates on this

**Comment by pratikshav13** [comment]
@saquino0827 Could you please share updates on this

**Comment by pratikshav13** [comment]
Could you please share updates on this

**Comment by saquino0827** [comment]
@pratikshav13 The Conversion Tool will be updated for 2022 QRDA-III files around October of this year.
