### ISSUE TITLE
QPP conversion tool 2022

### ISSUE THREAD

**Issue by NeetaRamani** [CMSgov/qpp-conversion-tool#1279]
hi,

Is this tool also updated for validating 2022 QRDAIII files?

**Comment by aljahnke54** [comment]
Hello,

It is now the end of August.  Is the lastest version of the QPP Conversion Tool (18.3.0) updated for the validation of the 2022 QRDA-III files?

**Comment by saquino0827** [comment]
Hi @aljahnke54,
The Conversion Tool is currently being updated and will not be ready for 2022 QRDA-III files until October.
