### ISSUE TITLE
NUMEx issue

### ISSUE THREAD

**Issue by abhisheka1993** [CMSgov/qpp-conversion-tool#1315]
Hi,
It seems NumEx the new section has been introduced in QPP exported file. Could you please let us know what kind of data needs to export in this section. Do you have any same data for it.

![NumEx](https://user-images.githubusercontent.com/55098368/203333067-d0cea234-dcaf-43f6-9d44-e9320d1c4be2.png)

**Comment by saquino0827** [comment]
Please see https://ecqi.healthit.gov/sites/default/files/ecqm/measures/CMS156v10.html for context of the data on the NUMEX field. As for sample data, we only have sample data we created via from the context above. I will upload this sample data in the repository and comment here when it is available.

**Comment by abhisheka1993** [comment]
Thanks resolved the issue.

**Comment by saquino0827** [comment]
As a follow up, a sample file is available here: https://github.com/CMSgov/qpp-conversion-tool/blob/develop/sample-files/2022/Y6-NUMEX-QRDA-III-MIPS.xml
