### ISSUE TITLE
Are you done with qpp conversion tool 2023 updates

### ISSUE THREAD

**Issue by abhisheka1993** [CMSgov/qpp-conversion-tool#1364]
Are you done with qpp conversion tool 2023 updates?
If not then when you will be finished it with?

**Comment by abhisheka1993** [comment]
Did you get a chance to reply?

**Comment by saquino0827** [comment]
Hi @abhisheka1993 
The ETA for updating QRDA-III to 2023 is around end the October to early November this year.

**Comment by abhisheka1993** [comment]
Are you done with qpp conversion tool 2023 updates?
If not then when you will be finished it with?

**Comment by mmveradigm** [comment]
Are we closer to a date for the qpp conversion tool 2023 updates?

**Comment by abhisheka1993** [comment]
Any updates ?
