### ISSUE TITLE
Update for Conversion Tool 2023 

### ISSUE THREAD

**Issue by mmveradigm** [CMSgov/qpp-conversion-tool#1383]
Do we have an ETA on when the conversion tool will be updated and how will we know that an update is available?

**Comment by saquino0827** [comment]
@mmveradigm We should be wrapping up all changes by next week.

**Comment by mmveradigm** [comment]
thank you @saquino0827, will there be a general notification that goes out letting us know that the tool has been updated to the 2023 standard?

**Comment by saquino0827** [comment]
No notification, but I will update here when it has been updated.

**Comment by abhisheka1993** [comment]
Any update on when we can get 2023 changes?

**Comment by abhisheka1993** [comment]
Hi,
Any update for the Conversion tool update completion?

**Comment by saquino0827** [comment]
Hi @abhisheka1993, the Conversion tool Develop branch has been updated with the latest 2023 changes.
