### ISSUE TITLE
Jar not found

### ISSUE THREAD

**Issue by abhisheka1993** [CMSgov/qpp-conversion-tool#1396]
Hi,
It is an urgent issue...!!
We have installed apache maven 3.8.2 and java 11 but still getting below exceptions
![JarError](https://github.com/CMSgov/qpp-conversion-tool/assets/55098368/ef64ede7-f6c5-497e-acfa-48013a8c406b)
![Maven](https://github.com/CMSgov/qpp-conversion-tool/assets/55098368/ac1c2562-b780-46a3-82e7-0ded9c35ddb2)
.

**Comment by saquino0827** [comment]
It looks like maven is not configured correctly as it is not able to recognize `mvn` as a command to build the jar.

**Comment by saquino0827** [comment]
The only issue I see similar to this is that the M2 home is not set properly. I don't use a windows machine but it looks like you need to 
1) Restart your machine after setting your `M2_Home`
2) Running the command `dir "%M2_HOME%\bin\mvn*`
