### ISSUE TITLE
CMS 156v11 Issue Version Specific Measure

### ISSUE THREAD

**Issue by abhisheka1993** [CMSgov/qpp-conversion-tool#1400]
We are using Version Specific Measure id 2c928084-808a-9589-0180-d74bf7b7164d for CMS156v11 but the file is not validating successfully. Could you please help us here.

**Comment by abhisheka1993** [comment]
![Screenshot 2023-12-11 105615](https://github.com/CMSgov/qpp-conversion-tool/assets/55098368/397152aa-dbaa-453b-841e-157693b71af1)

**Comment by abhisheka1993** [comment]
it's urgent we need to upgrade our customers with QPP updates. Could you please check and let us know if we need to use any other version specific measure id for cms156v11 or any other required changes.

**Comment by abhisheka1993** [comment]
Hi,
I have added xml file in zip. Could you please unzip and check it. Also FYI if we remove cms156v11 measure then able to validate file without any error. Could you please check and let us know if we need to make any changes.

[MaximEyesMIPSSubmission_2023-12-05.zip](https://github.com/CMSgov/qpp-conversion-tool/files/13643616/MaximEyesMIPSSubmission_2023-12-05.zip)

**Comment by saquino0827** [comment]
Hey @abhisheka1993 
The issue currently is with the Conversion Tool not allowing a NUMEX with CMS156v11. I will discuss with the team the issue and have an ETA with a fix soon.

**Comment by saquino0827** [comment]
As a work around, you can remove the NUMEX field in the XML and it should work without it.

**Comment by saquino0827** [comment]
I removed the file as I was unsure if there was PII in the file. Upon, double check the file itself did not contain PII as the value was test data.

**Comment by saquino0827** [comment]
The ETA for getting this fix in our Develop Branch will be by the end of this week.

**Comment by abhisheka1993** [comment]
Hi,
We have tried with removing 156v11 Pop2 NumEx as shown in IG 2023 '**C813AAC7-6D05-45D0-838D-467A837ECEC0**' but still issue exists. File is not validating successfully. Updated file is also attached. Please let me know any other changes we need to make at our end.
![156Pop2NumExcl](https://github.com/CMSgov/qpp-conversion-tool/assets/55098368/89d04dea-39cb-40cb-8e81-3695e0e788f2)
[MaximEyesMIPSSubmission_2023-12-05.zip](https://github.com/CMSgov/qpp-conversion-tool/files/13655788/MaximEyesMIPSSubmission_2023-12-05.zip)

**Comment by saquino0827** [comment]
@abhisheka1993 The fix has been merged into the Develop branch. Please rebuild the tool with that branch and try converting your original submission again.

**Comment by abhisheka1993** [comment]
Thanks issue has been fixed.
Is there any URL from there we can directly validate the file? On the new system, we always need to do all configurations related to MVN/ jdk etc.

**Comment by saquino0827** [comment]
I am not certain about new configurations of mvn and jdk and validating the file. I can check and see if the validating site is available to the public and provide a URL if so.

**Comment by abhisheka1993** [comment]
Yes please, if we get site that will be very helpful and time saving. 
Also please suggest any google group for this kind of discussion.

**Comment by saquino0827** [comment]
@abhisheka1993 This is a publicly available page for QPP submissions.
https://preview.qpp.cms.gov/api/submissions/public/docs/#/_ga%3D2.240701707.92125567.1702657956-805634992.1702657956
There is a validation URL for validating QPP-json. I am not aware of any google groups that discuss this testing.
