### ISSUE TITLE
Earliest Possible Date for Completed Conversion Tool

### ISSUE THREAD

**Issue by mmveradigm** [CMSgov/qpp-conversion-tool#1459]
What is the earliest date that the conversion tool would be ready for 2024? Last year it was early December just want to gauge where we are. 
Thank you.

**Comment by sivaksb** [comment]
Hi @mmveradigm, are you referring to the user testing or submission open date?  User testing - we are targeting by end of October.

**Comment by mmveradigm** [comment]
Hi @sivaksb , I believe user testing .... just wanting to know when the update for 2024 would be available so that we can pull it and update our tool to confirm if QRDA files will convert to qpp.json properly.

**Comment by sivaksb** [comment]
@mmveradigm The PY24 year changes are in develop branch.  Just note that, the entity IDs are not updated yet in this file - https://github.com/CMSgov/qpp-conversion-tool/blob/develop/converter/src/main/resources/pcf_apm_entity_ids.json.  We are expecting this data will be updated after October 28.

**Comment by mmveradigm** [comment]
Hello, when will the converter tool update be available for download? Last year we did not get notification until the first week of December.  This is the notification we got last year. Will we get something similar?

![Screenshot 2024-11-12 102619](https://github.com/user-attachments/assets/ec0c3bfb-4086-474f-a4ec-4e256abab897)

**Comment by mmveradigm** [comment]
Hello,
@sivaksb , are the updates to the tool now complete?

![Screenshot 2024-11-15 103754](https://github.com/user-attachments/assets/9f85f1f3-7009-4ff3-bcda-425d49572b82)

**Comment by sivaksb** [comment]
@mmveradigm Yes it is complete and ready for preliminary testing.
