### ISSUE TITLE
License question..(not an issue)

### ISSUE THREAD

**Issue by rajesh-nayak-cms** [CMSgov/qpp-conversion-tool#557]
Question about the license of this tool. The CC0 is no longer presented as an option on GitHub.com while creating repositories. I guess that the list of available option is pulled from https://choosealicense.com/licenses/ which also has its own gist. 

How can this repository be forked when the supporting CC0 license is no longer available on GitHub.com?

**Comment by halprin** [comment]
Hey there @rajesh-nayak-cms.

Regardless of what GitHub supports through https://choosealicense.com, the license of this code remains the Creative Commons Zero v1.0 Universal (CC0).  GitHub also states that they allow forking a repository regardless of the license.  Basically, it is up to you, not GitHub, to obey or disobey a license.

But, in any case, GitHub still supports CC0.  You still see it on in the top-right of our repository page and [here it is on choosealicense.com](https://choosealicense.com/licenses/cc0-1.0/).

I hope this helps!
