### ISSUE TITLE
QPP conversion tool configure locally

### ISSUE THREAD

**Issue by namratasingh20990** [CMSgov/qpp-conversion-tool#742]
#Configuration of this tool issue:
Cannot create a WAR file of this project. So how to configure this and deploy in apache tomcat to use the API locally?
How to use with Docker?

### Information
- OS & version:
- Java version: *(Run `$ java -version`.)*
- Docker version if using: *(Run `$ docker -v`.)*

### Expected behavior
*(Please be more descriptive than "This file should have created valid QPP."
Also, if you can attach a sample QRDA3 file ***without*** Personally Identifiable Information, that will make triage easier.)*

### Actual behavior
*(Please be more descriptive than "This file didn't create valid QPP.")*

### Steps to reproduce
1. *(Please include detailed steps.)*

### Other details
*(Tell us any other details you think are pertinent to this issue.)*

**Comment by omnivion** [comment]
The easiest way to deploy this locally would be with docker, or by first building the whole project with "mvn clean install", then running "mvn spring-boot:run" from within the rest-api directory
