### ISSUE TITLE
QRDA III is successfully converted but is rejected by QPP due to invalid measurement `value` field

### ISSUE THREAD

**Issue by nathandonato** [CMSgov/qpp-conversion-tool#844]
### Information
- OS, Java, and Docker versions are whatever is running on the production server as of 20180103

### Expected behavior
- QRDA III file is converted and submission is accepted

### Actual behavior
- QRDA III file is indeed converted, but submission is rejected due to invalid `value` field in the JSON for CMS 156 (`measureId 238`)
- Error file from QPP: [csv_error_file copy.csv.txt](https://github.com/CMSgov/qpp-conversion-tool/files/2728267/csv_error_file.copy.csv.txt) (txt extension added for Github)

### Steps to reproduce
1.  Navigate to the QPP production submission site: https://qpp.cms.gov/
2. Upload the following QRDA III file:  [cms156-failure.xml.txt](https://github.com/CMSgov/qpp-conversion-tool/files/2728270/cms156-failure.xml.txt) (txt extension added for Github)
3. Receive error

### Other details
- Note that the attached QRDA has fake data (name and TIN replaced)
- Apologies if there is a better place to submit this issue. We were instructed by CMS last year, "If you can create a QRDA III file that can be converted using this tool, then you can create one that can be successfully submitted to QPP." That, coupled with the opaqueness of the error message, meant that this was the best I could do to triangulate the source of the issue. Feel free to close and redirect me if needed.
- **Local difference**: I also tested the file on a local instance of the conversion tool and noted a difference in the `value` field: the one shown in the error message has `metadata` while the local one did not. Here's my local machine's info:

Conversion tool ref: `ed8e0ef3c`
OS: macOS Mojave 10.14
Java: 
```
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```
Docker: 18.06.1-ce-mac73

**Comment by nathandonato** [comment]
Hi, apologies since I know it's a busy time for all of us, but according to the [support](https://github.com/CMSgov/qpp-conversion-tool/blob/develop/.github/SUPPORT.md) document,  we expected a response to this within 2 business days. Since it's a failing submission for an actual provider, we're hoping to shed some light on this soon. Thanks for your time.

**Comment by JJonesNXT** [comment]
I'm a developer representing two other EHR systems, I'm following this item because we also have several providers failing with this same nonsense error. 

field 'value' in Submission.measurementSets[0].measurements[6] is invalid: --- huge wall of JSON content --- is invalid for measureId 238.

The measureId changes based on what is being submitted. Curiously, the same file passes the QPP sandbox site just fine. It only fails when a provider is submitting in a live environment.

**Comment by saquino0827** [comment]
Apologies for the late reply. We are currently looking into this as we have had issues submitted elsewhere.

**Comment by omnivion** [comment]
The fix for this is now in pull request.
