### ISSUE TITLE
xml producing an Unexpected EOF read on the socket error

### ISSUE THREAD

**Issue by ricochetbrown** [CMSgov/qpp-conversion-tool#848]
### Information
- OS & version: Windows 10
- Java version: *(Run `$ java -version`.)* 
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
- Docker version if using: *(Run `$ docker -v`.)*: 
Docker version 18.09.0

### Expected behavior
*(Please be more descriptive than "This file should have created valid QPP."
Also, if you can attach a sample QRDA3 file ***without*** Personally Identifiable Information, that will make triage easier.)* It doesn't let me upload the xml source file here, but I can send the mock file over through some other means if applicable. The file should upload just like the test 'valid-QRDA-III-latest.xml'

### Actual behavior
*(Please be more descriptive than "This file didn't create valid QPP.")* The curl result produces: Warning: setting file ./qrda-files/QRDACat3_20190109.xml  failed!
and
curl: (26) read function returned funny value
It looks like the overall issue is java.io.IOException: org.apache.tomcat.util.http.fileupload.FileUploadException: Unexpected EOF read on the socket

### Steps to reproduce
1. *(Please include detailed steps.) Run the curl using the file provided (through the means I can provide the file to you).

### Other details
*(Tell us any other details you think are pertinent to this issue.)*

**Comment by omnivion** [comment]
Please attach the file which gives an error with all PII data removed.

**Comment by ricochetbrown** [comment]
[QRDACat3_ 20190109_MockFile.zip](https://github.com/CMSgov/qpp-conversion-tool/files/2749657/QRDACat3_.20190109_MockFile.zip)

Mock file is attached. All information in it is made up.
