### ISSUE TITLE
XML files are reported to be valid, but converter says 'Validation errors exist'.

### ISSUE THREAD

**Issue by thomasclifford** [CMSgov/qpp-conversion-tool#860]
### Information
- OS & version:  Windows 10 
- Java version: *(Run `$ java -version`.)*  build 1.8.0_181-b13
- Docker version if using: *(Run `$ docker -v`.)*  n/a

### Expected behavior
Test CAT3 files (xml) are producing 'Validation errors exist', but analyst insists they have converted them 
successfully. (They're not responding to emails).

### Actual behavior
20190122 131331 INFO  ProcessQPP - Processing file: .\testfilesdir\ASG_CPC_CAT 3 TEST - SFTP.xml
20190122 131332 ERROR ProcessQPP - TransformException for file: Validation errors exist
20190122 131332 ERROR ProcessQPP - Stack Trace: 
gov.cms.qpp.conversion.model.error.TransformException: Validation errors exist
	at gov.cms.qpp.conversion.Converter.transform(Converter.java:90)

[ASG_CPC_CAT 3 TEST - SFTP.xml.txt](https://github.com/CMSgov/qpp-conversion-tool/files/2784118/ASG_CPC_CAT.3.TEST.-.SFTP.xml.txt)
[ASG_CPC_CAT 3 TEST_WU.xml.txt](https://github.com/CMSgov/qpp-conversion-tool/files/2784119/ASG_CPC_CAT.3.TEST_WU.xml.txt)
[ASG_CPC_CAT 3 TEST - SFTP.xml.txt](https://github.com/CMSgov/qpp-conversion-tool/files/2784123/ASG_CPC_CAT.3.TEST.-.SFTP.xml.txt)
	at ProcessQPP.main(ProcessQPP.java:81)

### Steps to reproduce
		String sourcePathAndFile = SOURCE_DIR + File.separator + fileToProcess.getName();
		Path sourcePath = Paths.get(sourcePathAndFile);
		log.info("Processing file: " + sourcePathAndFile );
		//Converter converter = new Converter(new PathSource(path));
		Converter converter = new Converter(new PathSource(sourcePath));
	
		JsonWrapper jsonWrapper = new JsonWrapper();
		try { 
			jsonWrapper = converter.transform();
		} catch( TransformException te ) { 
			log.error("TransformException for file: " + te.getMessage() );
			log.error( "Stack Trace: ", te );
		}

### Other details
*(Tell us any other details you think are pertinent to this issue.)*

[ASG_CPC_CAT3_TEST_WU.xml.txt](https://github.com/CMSgov/qpp-conversion-tool/files/2784126/ASG_CPC_CAT3_TEST_WU.xml.txt)
[ASG_CPC_CAT3_TEST_SFTP.xml.txt](https://github.com/CMSgov/qpp-conversion-tool/files/2784128/ASG_CPC_CAT3_TEST_SFTP.xml.txt)

**Comment by thomasclifford** [comment]
My work email is thomas.clifford@mihin.org.
Thanks...

**Comment by thomasclifford** [comment]
Also, I found a number of lines in each xml file (almost 950 in each one), that had an ending comment 
tag ('-->') without a space after the end of the comment, like '.-->', or ''.
The file editor I use, CrimsonEditor v4.7, shows the next line or group of lines as part of the comment, 
and I thought that would affect the parsing for the xml....

**Comment by thomasclifford** [comment]
the line above:  like '.-->' or ''.     should read:
like '.--> or
.....(CodeSystem: ConfidentialityCode 2.16.840.1.113883.5.25 STATIC) (CONF:711246).-->

**Comment by thomasclifford** [comment]
I think that I found the issue, but not sure.
The MIPS files I've been given have:
               
               <templateId root="2.16.840.1.113883.10.20.27.1.1" extension="2016-09-01"/>
               
               <templateId root="2.16.840.1.113883.10.20.27.1.2" extension="2016-11-01"/>

The valid QRDA file Converter uses for tests has:
               <templateId root="2.16.840.1.113883.10.20.27.1.1" extension="2017-06-01"/>
               <templateId root="2.16.840.1.113883.10.20.27.1.2" extension="2017-07-01"/>
So it appears the test files I've been given are 2016 format, not 2017 or 2018.
I'm checking into whether we can produce 2018-format files from our data.

**Comment by omnivion** [comment]
@thomasclifford any update on this?

**Comment by saquino0827** [comment]
Closed due to no update.
