### ISSUE TITLE
2019 Reporting Period

### ISSUE THREAD

**Issue by RyanGonet** [CMSgov/qpp-conversion-tool#877]
Hey there. I'm a developer for an EHR. We're updating our measures for the 2019 reporting period. Before releasing the updates, we need to confirm that our generated QRDA III files pass CMS validation.

Do you have an rough estimate on when the qpp-conversion-tool will be updated for the 2019 reporting period?

Thank you,
Ryan

**Comment by sfradkin** [comment]
@RyanGonet: Updates for the 2019 reporting period will most likely not be made until later this summer.  The goal is to have changes available in a developer preview/sandbox environment by early autumn.

**Comment by RyanGonet** [comment]
Thank you @sfradkin
