### ISSUE TITLE
CMS144 and CMS135 - Consolitated count getting displayed in Converted Json

### ISSUE THREAD

**Issue by Ferozsrs** [CMSgov/qpp-conversion-tool#919]
### Information

Today we validate the CMS135 and 144 with QPP tool, Files are converted to Json successfully but in the Json files, Consolidated data count getting displayed for multiple IPP measures(CMS 144 and CMS135)  

Same thing we did for CMS 145(this is also multiple ipp measures), IPP1 and Ipp2 data getting displayed separately in the Json as shown in the below screenshot2.

### Expected behavior
Two different data sections should be displayed for Multiple Ipp measures like 135,144. Here is the screenshot attached for your reference which works fine for CMS145

![image](https://user-images.githubusercontent.com/44632985/69795573-76233c80-11f2-11ea-9897-be6ecb59161b.png)

### Actual behavior
Consolitated data getting displayed for multiple ipp measures

Here is the screenshot attached for your reference which is not works fine for CMs144 and 135

![image](https://user-images.githubusercontent.com/44632985/69796237-a8816980-11f3-11ea-88b5-4622e20de5db.png)

### Steps to reproduce
1. Generated the QRDA III for CMS135 and 144 and Validate with QPP tool(locally), Files are converted to Json successfully but in the Json files, Consolidated data count getting displayed for multiple IPP measures(CMS 144 and CMS135)

**Comment by bijujoseph** [comment]
Thank you @Ferozsrs for bringing this to our attention. Will respond with updates shortly. cc: @saquino0827 , @omnivion , @KyleApfel

**Comment by saquino0827** [comment]
@Ferozsrs @bijujoseph 
This is expected behavior. There are a few measures that are Multi Performance rates in QRDA-III format, but are Consolidated Single Performance rates in QPP format. Please see the attached documentation here: https://confluence.cms.gov/pages/viewpage.action?spaceKey=QPPPRACTICE&title=QRDA+Conversion+from+Multiple+to+Single+Rate

**Comment by Ferozsrs** [comment]
Hi Team

Thanks for response.

CMS 145 also multiple ipp measures then count getting displayed in two different section and same is not work for CMS 135  and CMS 144? And  this is also multiple ipp measures from 2019 onwards. please suggest

Also,  We don't have access to the below link.





Regards
Feroz

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by saquino0827** [comment]
Hi @Ferozsrs ,

Both CMS135 and CMS144 have this behavior. Here is some of the documentation listed here.
```
CMS135/Measure id 005
For the purposes of this measure, a single performance rate can be calculated as follows:
Performance Rate = (Numerator 1 + Numerator 2)/ [(Denominator 1 - Denominator Exceptions 1) + (Denominator 2 - Denominator Exceptions 2)]
CMS144/Measure id 008
For the purposes of this measure, a single performance rate can be calculated as follows:
Performance Rate = (Numerator 1 + Numerator 2)/ [(Denominator 1 - Denominator Exceptions 1) + (Denominator 2 - Denominator Exceptions 2)]
```

**Comment by Ferozsrs** [comment]
Hi Team
Thank you so much for information,
It mean, New performance rate formula only applies to CMS135 and CmS144 only? but not for rest of the CQM measures right? Please Suggest

Just to information, In our CQM Report and QRDAIII file we are publising performance rate in two section, So do you thing we need to published in single performance rate regarding CMS135 and 144. or It is already taking care during conversion.Please Suggest

Thanks in Advance

Regards
Feroz

**Comment by saquino0827** [comment]
Hi @Ferozsrs ,
The measures that this new performance rate formula applies to are listed below:
  - CMS135/Measure id 005
  - CMS144/Measure id 008
  - CMS157/Measure id 143
  - CMS347/Measure id 438

You do not need to submit under a single performance rate as the conversion tool already handles this during conversion.

**Comment by Ferozsrs** [comment]
Thanks You So much Team for details information and closing tickets

Regards
Feroz
