### ISSUE TITLE
CMS22v7 - Measure GUID message confusion

### ISSUE THREAD

**Issue by johnmahoney88** [CMSgov/qpp-conversion-tool#924]
Hello-
Using the latest version of the Qrda3 conversion tool, finding that CMS22v7 conversions throwing errors on measure guid reference 40280382-610b-e7a4-0161-9a3a392c37d5 as error but guid appears in eCQM spec and IG.

excerpt from CMS22v7.xml
   <id root="40280382-610b-e7a4-0161-9a3a392c37d5"/>

CMS22v7 GUID from Qrda IG
https://ecqi.healthit.gov/sites/default/files/2019-CMS-QRDA-III-Eligible-Clinicians-and-EP-IG-Addendum-08022019-508.pdf
CMS22v7 measure GUID
40280382-610b-e7a4-0161-9a3a392c37d5

**Comment by saquino0827** [comment]
Hi @johnmahoney88 
What branch of the conversion tool are you working on? Please try using the develop branch if you are not. The master branch is using last years version of the application.

**Comment by saquino0827** [comment]
Closing. Feel free to open another issue if this issue still persists.
