### ISSUE TITLE
Unable to push the code

### ISSUE THREAD

**Issue by srikanth1986soa** [CMSgov/qpp-conversion-tool#943]
Hi Team,
I found the issue in the QRDAIII to Json vconversion.
I made the code change in the converter project.
I want to commit the changes. can you please give me permission

 modified:   converter/src/main/java/gov/cms/qpp/conversion/decode/ClinicalDocumentDecoder.java
        modified:   converter/src/main/resources/pathing/path-correlation.json
        modified:   converter/src/test/java/gov/cms/qpp/SingularAttributeTest.java
        modified:   converter/src/test/java/gov/cms/qpp/acceptance/CpcPlusRoundTripTest.java
        modified:   converter/src/test/java/gov/cms/qpp/conversion/encode/PiSectionEncoderMultiMeasureTest.java

### Information
- OS & version:
- Java version: *(Run `$ java -version`.)*
- Docker version if using: *(Run `$ docker -v`.)*

### Expected behavior
*(Please be more descriptive than "This file should have created valid QPP."
Also, if you can attach a sample QRDA3 file ***without*** Personally Identifiable Information, that will make triage easier.)*

### Actual behavior
*(Please be more descriptive than "This file didn't create valid QPP.")*

### Steps to reproduce
1. *(Please include detailed steps.)*

### Other details
*(Tell us any other details you think are pertinent to this issue.)*

**Comment by omnivion** [comment]
You just need to fork, then make a pull request from your fork. We do this as a security measure to protect our CI server.
